on:
  pull_request:
    branches:
      - master
    paths:
      - .github/workflows/*
      - _config.yml
      - assets/**
      - content/**
      - data/**
      - i18n/**
      - layouts/**
      - static/**

name: Site Build Testing

jobs:
  test:
    name: Testing
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout ScratchAddons/Website
        uses: actions/checkout@v2
        with:
          path: repo
      - name: Checkout ScratchAddons/website-i18n-script
        uses: actions/checkout@v2
        with:
          repository: ScratchAddons/website-i18n-script
          path: script
      - name: Checkout ScratchAddons/website-i18n
        uses: actions/checkout@v2
        with:
          repository: ScratchAddons/website-i18n
          path: i18n

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x 
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-

      - name: Execute localization script
        run: | 
          cd repo
          npm install --prefix ../script
          node ../script/src/ci/hugo-add-i18n.js

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: latest
          extended: true
      - name: Build site
        run: |
          cd repo
          hugo --gc
          
      - name: Upload build
        uses: actions/upload-artifact@v2
        with:
          name: public
          path: ./repo/public
      - name: Upload whole repo (check i18n)
        uses: actions/upload-artifact@v2
        with:
          name: public
          path: ./repo